### ISSUE TITLE
Minimum node version

### ISSUE THREAD

**Issue by dmdque** [okcompute/esctags#2]
What's the minimum version of node? Works fine with v6.2.1, but with v0.10.32 I get:
```
/Users/danielq/.nvm/v0.10.32/lib/node_modules/es-ctags/src/command-line.js:3
const path = require('path')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/danielq/.nvm/v0.10.32/lib/node_modules/es-ctags/bin/es-ctags:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by okcompute** [comment]
It requires at the minimum node 4.0.
